/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppMain: typeof import('./src/layout/components/AppMain.vue')['default']
    Breadcrumb: typeof import('./src/layout/components/Breadcrumb/index.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Header: typeof import('./src/layout/components/Header.vue')['default']
    IEpAim: typeof import('~icons/ep/aim')['default']
    IEpExpand: typeof import('~icons/ep/expand')['default']
    IEpFold: typeof import('~icons/ep/fold')['default']
    IEpMinus: typeof import('~icons/ep/minus')['default']
    IEpPlus: typeof import('~icons/ep/plus')['default']
    IEpPlusPosition: typeof import('~icons/ep/plus-position')['default']
    IEpPosition: typeof import('~icons/ep/position')['default']
    IEpRefresh: typeof import('~icons/ep/refresh')['default']
    Logo: typeof import('./src/layout/components/Sidebar/logo.vue')['default']
    Navbar: typeof import('./src/layout/components/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Settings: typeof import('./src/layout/components/Settings/index.vue')['default']
    Sidebar: typeof import('./src/layout/components/Sidebar/index.vue')['default']
    SidebarItem: typeof import('./src/layout/components/Sidebar/SidebarItem.vue')['default']
    SidebarItemLink: typeof import('./src/layout/components/Sidebar/SidebarItemLink.vue')['default']
    Slider: typeof import('./src/layout/components/Slider.vue')['default']
    TagsView: typeof import('./src/layout/components/TagsView/index.vue')['default']
  }
}
